name: CDelivery

on:
  push:
    branches: [ main ]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43

  draft_release:
    name: Draft a release
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - name: Draft the release
      id: release-drafter
      uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
      with:
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
