name: CDelivery

on:
  push:
    branches: [ main ]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@90071c65175ec9fe440689658750fac7db600f4c

  draft_release:
    name: Draft a release
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Draft the release
      id: release-drafter
      uses: release-drafter/release-drafter@e5ccf147077e46b0225a80bbe314d795d77bb7a2
      with:
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
